  
export const USER_LOADING = "USER_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SUCCESS_MSG = "GET_SUCCESS_MSG";
export const RESET_ALL_STATE = "RESET_ALL_STATE";
export const RESET_SUCCESS_STATE = "RESET_SUCCESS_STATE";
export const RESET_ERROR_STATE = "RESET_ERROR_STATE";
export const CURRENT_USER_INFO = "CURRENT_USER_INFO";
export const SET_USER_PROJECTS = "SET_USER_PROJECTS";
export const SET_USER_PODS = "SET_USER_PODS";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const USER_LOADING_STOP = "USER_LOADING_STOP";
export const SET_PROJECT_USERS = "SET_PROJECT_USERS";