region                    = ["us-central1", "us-west1", "us-east4"]
vpc_name                  = "masters-295b"
zone                      = ["us-central1-f","us-west1-a", "us-east4-b"]
project_name              = "edge-platform-cmpe-295b"
k8s_worker_node_count     = 1
edge_node_count           = 1
credentials_file_location = "/Users/akshay/Downloads/edge-platform-cmpe-295b-e00bfe08b748.json"
ssh_user                  = "akshay"
db_user_name              = "platform"
db_password               = "EdgePlatform#Pass_999"